### PR TITLE
SONATA sim config updates

### PR DESCRIPTION
**Pull request by WeinaJi**
Remove key "synapses_init_depleted" in "conditions" section (BBPBGLIB-968)
 Move key "spike_location" from "run" to "conditions" (BBPBGLIB-914)

### CODE REVIEW

**Review by jorblancoa — APPROVED** [review]

**Comment by WeinaJi** [comment]
Hi @mgeplf , here are the updates of sonata simulation config requested by users, as well as the changes in libsonata parser https://github.com/BlueBrain/libsonata/pull/245
Do you have any comment on both PRs? Can I go ahead to merge? We will update the blueconfig converter afterwards.

**Comment by mgeplf** [comment]
I was off Friday, and other things have come up, I'll review it shortly.
It would be worthwhile to get sign-off on this PR this from scientists, too, so they are all kept up to date.

**Comment by WeinaJi** [comment]
Hello @anilbey @seirios @andrisecker  
Two keys will be modified in the SONATA simulation config as we discussed in [BBPBGLIB-968](https://bbpteam.epfl.ch/project/issues/browse/BBPBGLIB-968) and [BBPBGLIB-914](https://bbpteam.epfl.ch/project/issues/browse/BBPBGLIB-914) . Please have a look at the spec.

**Comment by mgeplf** [comment]
Tagging @MWolfR, @romani79, @wvangeit  as well.

**Comment by andrisecker** [comment]
looks good!

**Comment by mgeplf** [comment]
@andrisecker Please don't merge things that aren't your changes; we're still hoping for feed back from others.

I'll revert if there is anything blocking us, but unless someone speaks up in the next few days, we'll keep it.

**Pull request merged**
