### PR TITLE
clear up SONATA node_sets_file language

### PR DESCRIPTION
**Pull request by mgeplf**
* explain interaction between circuit_config and simulation_config

### CODE REVIEW

**Comment by mgeplf** [comment]
@jamesgking, @pramodk, @jdcourcol, @MWolfR, @jplanasc, @NadirRoGue
Please add other people to loop them in.

**Comment by NadirRoGue** [comment]
Thanks for the heads up.

**Comment by WeinaJi** [comment]
LGTM, thanks!

**Review by matz-e — APPROVED** [review]

**Review by jdcourcol — APPROVED** [review]

**Comment by mgeplf** [comment]
We seem to have a consensus here; if I don't hear any objects, I will merge tomorrow morning.

**Pull request merged**
